name: Hourly weather action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas sqlite3

      - name: Run weather script
        env: 
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Running weather script with secret"
          python app.py
